language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - node_modules
script:
  - yarn test
  - yarn export
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: out
  # Push the artifacts to the gh-pages branch if the deployment is on 'master'.
  on:
    branch: master
